// <auto-generated />
using System;
using ArtGalleryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArtGalleryAPI.Migrations
{
    [DbContext(typeof(ArtGalleryDbContext))]
    [Migration("20260413122411_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtGalleryAPI.Models.ArtType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Technique")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ArtTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Traditional Aboriginal art using dots to create patterns and hide sacred meanings",
                            Name = "Dot Painting",
                            Region = "Central Desert",
                            Technique = "Acrylic dots using sticks, brushes, or dowels"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Painting on eucalyptus bark using natural ochres",
                            Name = "Bark Painting",
                            Region = "Arnhem Land",
                            Technique = "Natural pigments on prepared bark"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ancient paintings and engravings on rock surfaces",
                            Name = "Rock Art",
                            Region = "Throughout Australia",
                            Technique = "Ochre, charcoal, clay, and engraving"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Traditional basket weaving and fiber art",
                            Name = "Weaving",
                            Region = "Coastal and River Regions",
                            Technique = "Pandanus, grasses, and natural fibers"
                        });
                });

            modelBuilder.Entity("ArtGalleryAPI.Models.Artifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Dimensions")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Medium")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Story")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("YearCreated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtTypeId")
                        .HasDatabaseName("IX_Artifacts_ArtTypeId");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("IX_Artifacts_ArtistId");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Artifacts_Title");

                    b.HasIndex("YearCreated")
                        .HasDatabaseName("IX_Artifacts_YearCreated");

                    b.HasIndex("IsAvailable", "ArtTypeId")
                        .HasDatabaseName("IX_Artifacts_Available_Type");

                    b.ToTable("Artifacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtTypeId = 1,
                            ArtistId = 1,
                            CreatedAt = new DateTime(2026, 4, 13, 12, 24, 10, 817, DateTimeKind.Utc).AddTicks(9510),
                            Description = "A vibrant abstract representation of the artist's ancestral lands",
                            Dimensions = "151cm x 121cm",
                            IsAvailable = false,
                            Medium = "Acrylic on Canvas",
                            Price = 250000.00m,
                            Story = "This painting represents the Bush Yam Dreaming, a story passed down through generations of the Alhalkere women.",
                            Title = "Alhalkere Country",
                            YearCreated = 1991
                        },
                        new
                        {
                            Id = 2,
                            ArtTypeId = 1,
                            ArtistId = 2,
                            CreatedAt = new DateTime(2026, 4, 13, 12, 24, 10, 817, DateTimeKind.Utc).AddTicks(9510),
                            Description = "A major collaborative work depicting the ancestral fire dreaming",
                            Dimensions = "210cm x 560cm",
                            IsAvailable = false,
                            Medium = "Synthetic polymer paint on canvas",
                            Price = 2500000.00m,
                            Story = "Tells the story of Lungkata, the Blue Tongue Lizard, who brought fire to the people of the Western Desert.",
                            Title = "Warlugulong",
                            YearCreated = 1977
                        },
                        new
                        {
                            Id = 3,
                            ArtTypeId = 3,
                            ArtistId = 3,
                            CreatedAt = new DateTime(2026, 4, 13, 12, 24, 10, 817, DateTimeKind.Utc).AddTicks(9510),
                            Description = "Watercolour landscape featuring the iconic ghost gum trees",
                            Dimensions = "35cm x 53cm",
                            IsAvailable = false,
                            Medium = "Watercolour on paper",
                            Price = 45000.00m,
                            Story = "Depicts the MacDonnell Ranges near Alice Springs, painted en plein air.",
                            Title = "Ghost Gum",
                            YearCreated = 1955
                        },
                        new
                        {
                            Id = 4,
                            ArtTypeId = 1,
                            ArtistId = 4,
                            CreatedAt = new DateTime(2026, 4, 13, 12, 24, 10, 817, DateTimeKind.Utc).AddTicks(9520),
                            Description = "Abstract dot painting in vibrant reds, oranges, and yellows",
                            Dimensions = "183cm x 244cm",
                            IsAvailable = false,
                            Medium = "Synthetic polymer paint on linen",
                            Price = 180000.00m,
                            Story = "Represents the artist's birthplace and the ancestral creation stories of the Western Desert.",
                            Title = "Irrunytju",
                            YearCreated = 2007
                        },
                        new
                        {
                            Id = 5,
                            ArtTypeId = 1,
                            ArtistId = 1,
                            CreatedAt = new DateTime(2026, 4, 13, 12, 24, 10, 817, DateTimeKind.Utc).AddTicks(9520),
                            Description = "Contemporary dot painting exploring women's ceremonial sites",
                            Dimensions = "122cm x 150cm",
                            IsAvailable = true,
                            Medium = "Acrylic on Belgian linen",
                            Price = 32000.00m,
                            Story = "Depicts the journey of ancestral women across the desert country, gathering food and performing ceremonies.",
                            Title = "Mina Mina Dreaming",
                            YearCreated = 2005
                        },
                        new
                        {
                            Id = 6,
                            ArtTypeId = 2,
                            ArtistId = 2,
                            CreatedAt = new DateTime(2026, 4, 13, 12, 24, 10, 817, DateTimeKind.Utc).AddTicks(9520),
                            Description = "Traditional bark painting showing traditional hunting tools",
                            Dimensions = "120cm x 80cm",
                            IsAvailable = true,
                            Medium = "Natural ochres on eucalyptus bark",
                            Price = 28000.00m,
                            Story = "Depicts the traditional woven fish traps used by the Yolngu people in Arnhem Land.",
                            Title = "Fish Trap",
                            YearCreated = 1985
                        });
                });

            modelBuilder.Entity("ArtGalleryAPI.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClanGroup")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeceased")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageGroup")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Region")
                        .HasDatabaseName("IX_Artists_Region");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "One of Australia's most significant contemporary artists, known for her abstract expressionist works.",
                            BirthDate = new DateTime(1910, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClanGroup = "Alhalkere",
                            CreatedAt = new DateTime(2026, 4, 13, 12, 24, 10, 817, DateTimeKind.Utc).AddTicks(9480),
                            DeathDate = new DateTime(1996, 9, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Emily",
                            IsDeceased = true,
                            LanguageGroup = "Anmatyerre",
                            LastName = "Kame Kngwarreye",
                            Region = "Utopia, Northern Territory"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Pioneer of the contemporary Aboriginal art movement, famous for his dot paintings.",
                            BirthDate = new DateTime(1932, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClanGroup = "Anmatyerre",
                            CreatedAt = new DateTime(2026, 4, 13, 12, 24, 10, 817, DateTimeKind.Utc).AddTicks(9490),
                            DeathDate = new DateTime(2002, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Clifford",
                            IsDeceased = true,
                            LanguageGroup = "Anmatyerre",
                            LastName = "Possum Tjapaltjarri",
                            Region = "Napperby Station, Northern Territory"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "First famous Aboriginal watercolour artist, known for his landscape paintings of Central Australia.",
                            BirthDate = new DateTime(1902, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClanGroup = "Western Arrernte",
                            CreatedAt = new DateTime(2026, 4, 13, 12, 24, 10, 817, DateTimeKind.Utc).AddTicks(9490),
                            DeathDate = new DateTime(1959, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Albert",
                            IsDeceased = true,
                            LanguageGroup = "Arrernte",
                            LastName = "Namatjira",
                            Region = "Hermannsburg, Northern Territory"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Known for vibrant abstract paintings representing his country and ancestral stories.",
                            BirthDate = new DateTime(1935, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ClanGroup = "Pitjantjatjara",
                            CreatedAt = new DateTime(2026, 4, 13, 12, 24, 10, 817, DateTimeKind.Utc).AddTicks(9500),
                            DeathDate = new DateTime(2017, 11, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Yannima",
                            IsDeceased = true,
                            LanguageGroup = "Pitjantjatjara",
                            LastName = "Tommy Watson",
                            Region = "Irrunytju, Western Australia"
                        });
                });

            modelBuilder.Entity("ArtGalleryAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ArtGalleryAPI.Models.Artifact", b =>
                {
                    b.HasOne("ArtGalleryAPI.Models.ArtType", "ArtType")
                        .WithMany("Artifacts")
                        .HasForeignKey("ArtTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtGalleryAPI.Models.Artist", "Artist")
                        .WithMany("Artifacts")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtType");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("ArtGalleryAPI.Models.ArtType", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("ArtGalleryAPI.Models.Artist", b =>
                {
                    b.Navigation("Artifacts");
                });
#pragma warning restore 612, 618
        }
    }
}
